### ISSUE TITLE
Save django and geoserver logs to be exported as artifacts

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform2#48]
Sometime the `django` serve does not start during tests (see https://ci.openquake.org/job/master_oq-platform2/693/ and https://ci.openquake.org/job/master_oq-platform2/691/) but we loose the information about what was going wrong because we do not have access to the server logs.

We should save logs (`djnago` and maybe `geoserver` too) on a text file that then is exported by jenkins as an artifact, like we do on `oq-platform`.

**Comment by hascar** [comment]
Fixed with this: https://github.com/gem/oq-platform2/tree/artifacts_log
