### ISSUE TITLE
Installation Error (cp: cannot stat '/root/oq_install.sh': No such file or directory)

### ISSUE THREAD

**Issue by xfeep** [gem/oq-platform2#71]
When I tried to install oq-platform2 by this command

``` 
## first download release 2.2.1 and extract the tar.gz file
sudo -H oq-platform2-2.2.1/openquakeplatform/bin/deploy.sh
```

It reported an error :
```
cp: cannot stat '/root/oq_install.sh': No such file or directory
```
It was caused by line 221:
```
    cp $HOME/oq_install.sh .
```

**Comment by daniviga** [comment]
Although this project is not yet ready to be installed by users (#72) and support is not provided in that sense you can have a look at https://github.com/gem/oq-platform2/blob/master/verifier-guest.sh as a starting point for an installation. You must use Ubuntu 16.04 LTS.
