### ISSUE TITLE
Supplemental imformation is truncated

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform2#86]
The supplemental information filed on objects is truncated after few words. This is hiding from the user some important information like the copyright.

It's a regression since in the old platform we were showing all of its content.

**Comment by daniviga** [comment]
This may apply also to other fields, like 'purpose'.

**Comment by hascar** [comment]
Please, put an example.

**Comment by daniviga** [comment]
See https://platform.openquake.org/maps/80



**OLD**
![Screenshot from 2019-06-25 11-44-50](https://user-images.githubusercontent.com/1818657/60088527-1a362280-973f-11e9-914f-9053d6f32a04.png)

***

**NEW**
![Screenshot from 2019-06-25 11-44-00](https://user-images.githubusercontent.com/1818657/60088533-1bffe600-973f-11e9-8ac5-38f1741cc094.png)

**Comment by hascar** [comment]
Thanks
