### ISSUE TITLE
Tomcat log flooded by GeoFence errors

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform2#95]
The tomcat log in production is full (more than 1/s) of errors like

```
29 Aug 10:07:04 WARN [geofence.internal] - GeoFence was not able to find any matching user on Security Context amd Services.
Aug 29, 2019 10:07:04 AM org.geoserver.security.GeoServerRestRoleService connectToRESTEndpoint
WARNING: null
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8000 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
```

The log, which has been rotated less than 3 hrs ago is already almost 90MB big.

It looks like that tomcat is trying to contact a non existing service (`localhost:8000`)

**Comment by hascar** [comment]
This appens only when is used "Social Vulnerability Integrated Risk Viewer" application.
Need to investigate and i donn't think that is a geofence's bug
